services:
  error_and_log_service:
    build:
      context: .
    container_name: error_and_log_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    networks:
      - ucomand-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001" 
    volumes:
      - minio_data:/data
    networks:
      - ucomand-network

networks:
  ucomand-network:
    external: true

volumes:
  minio_data:
