services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    networks:
      - ucomand-network

networks:
  ucomand-network:
    external: true