services:
  error_and_log_service:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    networks:
      - ucomand-network

networks:
  ucomand-network:
    external: true